server:
  port: 8300

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: studentModule
          uri: lb://student-service
          predicates:
            - Path=/student/**
        - id: courseModule
          uri: lb://course-service
          predicates:
            - Path=/course/**
#          filters:
#          - name: requestSize
#            args:
#              Maxsize: 50000000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8400/eureka


